In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [23]:
table1 = pd.read_csv('First_location.csv')
table2 = pd.read_csv('Second_location.csv')
table3 = pd.read_csv('Third_location.csv')
table4 = pd.read_csv('four_location.csv')
table5 = pd.read_csv('five_location.csv')
table6 = pd.read_csv('six_location.csv')
table7 = pd.read_csv('seven_location.csv')
table8 = pd.read_csv('eight_location.csv')
table9 = pd.read_csv('nine_location.csv')

In [10]:
columns = ['FitNet Studio & Clinic', 'FitNet Health Club', 'FitNet Gym & Clinic', 'FitNet Gym Centre',
          'FitNet Health Paradise', 'FitNet Pro FitNess', 'FitNet Body Construction', 'FitNet Health Planet', 'FitNet Muscle Den']

In [13]:
table['Duration'][0]

'Monthly'

In [28]:
df = pd.DataFrame()
df['Name'] = columns
df

                       Name
0    FitNet Studio & Clinic
1        FitNet Health Club
2       FitNet Gym & Clinic
3         FitNet Gym Centre
4    FitNet Health Paradise
5        FitNet Pro FitNess
6  FitNet Body Construction
7      FitNet Health Planet
8         FitNet Muscle Den

In [27]:
location = [table1['Location'][0], table2['Location'][0], table3['Location'][0], table4['Location'][0],
           table5['Location'][0], table6['Location'][0], table7['Location'][0], table8['Location'][0],
           table9['Location'][0]]

location

['Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107',
 'Near, 9A, Ashutosh Chowdary Ave, Ballygunge Place, Ballygunge, Kolkata, West Bengal 700019',
 'Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316',
 'APC Tower, 20, Kali Prasanna Kumar St, Belur, Bally, Howrah, West Bengal 711201',
 '6-10, Ranikuthi, Samajgarh, Tollygunge, Kolkata, West Bengal 700040',
 '1st, Floor, 84, Dunlop Flyover, Dunlop, Bonhoogly, Ashokgarh, Kolkata, West Bengal 700108',
 'Naskar Bagan, South Dumdum, West Bengal 700055',
 'Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316',
 'CF-140, 4th Cross Rd, CF Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064']

In [30]:
pd.set_option('display.max_colwidth', None)
df['Location'] = location
df

,Name,Location
0,FitNet Studio & Clinic,"Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107"
1,FitNet Health Club,"Near, 9A, Ashutosh Chowdary Ave, Ballygunge Place, Ballygunge, Kolkata, West Bengal 700019"
2,FitNet Gym & Clinic,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316"
3,FitNet Gym Centre,"APC Tower, 20, Kali Prasanna Kumar St, Belur, Bally, Howrah, West Bengal 711201"
4,FitNet Health Paradise,"6-10, Ranikuthi, Samajgarh, Tollygunge, Kolkata, West Bengal 700040"
5,FitNet Pro FitNess,"1st, Floor, 84, Dunlop Flyover, Dunlop, Bonhoogly, Ashokgarh, Kolkata, West Bengal 700108"
6,FitNet Body Construction,"Naskar Bagan, South Dumdum, West Bengal 700055"
7,FitNet Health Planet,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316"
8,FitNet Muscle Den,"CF-140, 4th Cross Rd, CF Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064"

In [31]:
table1

,Duration,Charges,Facilities,Location,Facility1,Facility2,Facility3,Facility4,Facility5
0,Monthly,1500.0,"No free dietains sessions, Service Locker Room, Fitness Assessment, Morning Slot, Health Checkup","Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",No free dietains sessions,Service Locker Room,Fitness Assessment,Morning Slot,Health Checkup
1,Quarterly,4000.0,"1 free dietains sessions, Service Locker Room, Fitness Assessment, Morning Slot, Health Checkup","Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",1 free dietains sessions,Service Locker Room,Fitness Assessment,Morning Slot,Health Checkup
2,Half-Yearly,4999.0,"2 free dietains sessions, Service Locker Room, Fitness Assessment, Morning Slot, Health Checkup","Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",2 free dietains sessions,Service Locker Room,Fitness Assessment,Morning Slot,Health Checkup
3,Yearly,5999.0,"4 free dietains sessions, Service Locker Room, Fitness Assessment, Morning Slot, Health Checkup","Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",4 free dietains sessions,Service Locker Room,Fitness Assessment,Morning Slot,Health Checkup

In [33]:
moncharge = [table1['Charges'][0],table2['Charges'][0],table3['Charges'][0],table4['Charges'][0],table5['Charges'][0],
            table6['Charges'][0],table7['Charges'][0],table8['Charges'][0],table9['Charges'][0]]
moncharge

[1500.0, 1500.0, 1200.0, 1500.0, 1500.0, 1500.0, 1500.0, 1200.0, 1500.0]

In [34]:
df['Monthly Charges'] = moncharge
df

,Name,Location,Monthly Charges
0,FitNet Studio & Clinic,"Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",1500.0
1,FitNet Health Club,"Near, 9A, Ashutosh Chowdary Ave, Ballygunge Place, Ballygunge, Kolkata, West Bengal 700019",1500.0
2,FitNet Gym & Clinic,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0
3,FitNet Gym Centre,"APC Tower, 20, Kali Prasanna Kumar St, Belur, Bally, Howrah, West Bengal 711201",1500.0
4,FitNet Health Paradise,"6-10, Ranikuthi, Samajgarh, Tollygunge, Kolkata, West Bengal 700040",1500.0
5,FitNet Pro FitNess,"1st, Floor, 84, Dunlop Flyover, Dunlop, Bonhoogly, Ashokgarh, Kolkata, West Bengal 700108",1500.0
6,FitNet Body Construction,"Naskar Bagan, South Dumdum, West Bengal 700055",1500.0
7,FitNet Health Planet,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0
8,FitNet Muscle Den,"CF-140, 4th Cross Rd, CF Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064",1500.0

In [35]:
quarcharge = [table1['Charges'][1],table2['Charges'][1],table3['Charges'][1],table4['Charges'][1],table5['Charges'][1],
            table6['Charges'][1],table7['Charges'][1],table8['Charges'][1],table9['Charges'][1]]
quarcharge

[4000.0, 4000.0, 3000.0, 4000.0, 4000.0, 4000.0, 4000.0, 3000.0, 4000.0]

In [36]:
df['Quarterly Charges'] = quarcharge
df

,Name,Location,Monthly Charges,Quarterly Charges
0,FitNet Studio & Clinic,"Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",1500.0,4000.0
1,FitNet Health Club,"Near, 9A, Ashutosh Chowdary Ave, Ballygunge Place, Ballygunge, Kolkata, West Bengal 700019",1500.0,4000.0
2,FitNet Gym & Clinic,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0,3000.0
3,FitNet Gym Centre,"APC Tower, 20, Kali Prasanna Kumar St, Belur, Bally, Howrah, West Bengal 711201",1500.0,4000.0
4,FitNet Health Paradise,"6-10, Ranikuthi, Samajgarh, Tollygunge, Kolkata, West Bengal 700040",1500.0,4000.0
5,FitNet Pro FitNess,"1st, Floor, 84, Dunlop Flyover, Dunlop, Bonhoogly, Ashokgarh, Kolkata, West Bengal 700108",1500.0,4000.0
6,FitNet Body Construction,"Naskar Bagan, South Dumdum, West Bengal 700055",1500.0,4000.0
7,FitNet Health Planet,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0,3000.0
8,FitNet Muscle Den,"CF-140, 4th Cross Rd, CF Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064",1500.0,4000.0

In [37]:
hcharge = [table1['Charges'][2],table2['Charges'][2],table3['Charges'][2],table4['Charges'][2],table5['Charges'][2],
            table6['Charges'][2],table7['Charges'][2],table8['Charges'][2],table9['Charges'][2]]

ycharge = [table1['Charges'][3],table2['Charges'][3],table3['Charges'][3],table4['Charges'][3],table5['Charges'][3],
            table6['Charges'][3],table7['Charges'][3],table8['Charges'][3],table9['Charges'][3]]
df['Half yearly Charges'] = hcharge
df['Yearly Charges'] = ycharge
df

,Name,Location,Monthly Charges,Quarterly Charges,Half yearly Charges,Yearly Charges
0,FitNet Studio & Clinic,"Plot No. - 23, 2061, Rajdanga Main Rd, P.O, Block BE, Sector B, East Kolkata Twp, Kolkata, West Bengal 700107",1500.0,4000.0,4999.0,5999.0
1,FitNet Health Club,"Near, 9A, Ashutosh Chowdary Ave, Ballygunge Place, Ballygunge, Kolkata, West Bengal 700019",1500.0,4000.0,6000.0,10000.0
2,FitNet Gym & Clinic,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0,3000.0,5000.0,8000.0
3,FitNet Gym Centre,"APC Tower, 20, Kali Prasanna Kumar St, Belur, Bally, Howrah, West Bengal 711201",1500.0,4000.0,6000.0,10000.0
4,FitNet Health Paradise,"6-10, Ranikuthi, Samajgarh, Tollygunge, Kolkata, West Bengal 700040",1500.0,4000.0,6000.0,10000.0
5,FitNet Pro FitNess,"1st, Floor, 84, Dunlop Flyover, Dunlop, Bonhoogly, Ashokgarh, Kolkata, West Bengal 700108",1500.0,4000.0,6000.0,10000.0
6,FitNet Body Construction,"Naskar Bagan, South Dumdum, West Bengal 700055",1500.0,4000.0,6000.0,10000.0
7,FitNet Health Planet,"Dilshan Apartment, opp. M Bazar, Bazarpara, Uluberia, Howrah, West Bengal 711316",1200.0,3000.0,5000.0,8000.0
8,FitNet Muscle Den,"CF-140, 4th Cross Rd, CF Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064",1500.0,4000.0,6000.0,10000.0

df.to_csv('name_location.csv', index = False)